site_name: CJH
site_url: https://github.com/chenjh726/chenjh726.github.io/settings
site_author: chenjh726
theme:
 name: material
 features:
  - content.code.copy
 language: zh
 palette:
  primary: indigo
  accent: indigo
extra_css:
  - styles/title_color.css