site_name: CJH
site_url: https://github.com/chenjh726/chenjh726.github.io/
site_author: chenjh726

theme:
 name: material
 features:
  - content.code.copy
 language: zh
 palette:
  primary: indigo
  accent: indigo

plugins:
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg